couchpotato:
  image: ipsq/docker-bingebox-couchpotato:latest

sonarr:
  image: ipsq/docker-sonarr-couchpotato:latest

plex:
  image: ipsq/docker-plex-couchpotato:latest

nzbget:
  image: ipsq/docker-nzbget-couchpotato:latest

headphones:
  image: ipsq/docker-headphones-couchpotato:latest

deluge:
  image: ipsq/docker-deluge-couchpotato:latest

nginx:
  image: ipsq/docker-nginx-couchpotato:latest
  ports:
   - "80:80"
  links:
   - couchpotato
   - sonarr
   - plex
   - nzbget
   - headphones
   - deluge