couchpotato:
  image: ipsq/docker-bingebox-couchpotato:latest
  environment:
   - COUCHPOTATO_PASSWORD=${COUCHPOTATO_PASSWORD}
  links:
   - nzbget
   - deluge

deluge:
  image: ipsq/docker-deluge-couchpotato:latest
  environment:
   - DELUGE_PASSWORD=${DELUGE_PASSWORD}

headphones:
  image: ipsq/docker-headphones-couchpotato:latest
  environment:
   - HEADPHONES_PASSWORD=${HEADPHONES_PASSWORD}
  links:
   - nzbget
   - deluge

nzbget:
  image: ipsq/docker-nzbget-couchpotato:latest
  environment:
   - NZBGET_PASSWORD=${NZBGET_PASSWORD}

plex:
  image: ipsq/docker-plex-couchpotato:latest
  environment:
     - PLEX_PASSWORD=${PLEX_PASSWORD}

sonarr:
  image: ipsq/docker-sonarr-couchpotato:latest
  environment:
   - SONARR_PASSWORD=${SONARR_PASSWORD}
  links:
   - nzbget
   - deluge

nginx:
  image: ipsq/docker-nginx-couchpotato:latest
  ports:
   - "80:80"
  links:
   - couchpotato
   - sonarr
   - plex
   - nzbget
   - headphones
   - deluge