couchpotato:
  build: ../couchpotato
  environment:
   - COUCHPOTATO_PASSWORD=${COUCHPOTATO_PASSWORD}
  links:
   - nzbget
   - deluge

deluge:
  build: ../deluge
  environment:
   - DELUGE_PASSWORD=${DELUGE_PASSWORD}

headphones:
  build: ../headphones
  environment:
   - HEADPHONES_PASSWORD=${HEADPHONES_PASSWORD}
  links:
   - nzbget
   - deluge

nzbget:
  build: ../nzbget
  environment:
   - NZBGET_PASSWORD=${NZBGET_PASSWORD}

plex:
  build: ../plex
  environment:
     - PLEX_PASSWORD=${PLEX_PASSWORD}

sonarr:
  build: ../sonarr
  environment:
   - SONARR_PASSWORD=${SONARR_PASSWORD}
  links:
   - nzbget
   - deluge

nginx:
  build: ../nginx
  ports:
   - "80:80"
  links:
   - couchpotato
   - sonarr
   - plex
   - nzbget
   - headphones
   - deluge